### ISSUE TITLE
Holding down hjkl keys doesn't keep moving...

### ISSUE THREAD

**Issue by hillbrad** [player-two/brackets-vim#1]
I notice that navigating in cmd mode using the hjkl keys requires me to do a individual key press for every cursor movement.  I can't hold down a key to keep the cursor moving.

Platform: OSX 10.9

**Comment by sbruchmann** [comment]
I can’t reproduce this behavior on my system:
- OS X 10.9.3
- Brackets sprint 41 development build 0.41.0-0 (master [085893af1](https://github.com/adobe/brackets/commit/085893af14d77c2d414aad7c0ea723c84b9ec3f6))
- Brackets Vim 0.2.3

**Comment by hillbrad** [comment]
Hmm.. could repro for a bit, and now it's gone.  :/   Oh well, happy
vimming now!  Thanks for a cool extension.
