### ISSUE TITLE
Normal mode `ci)` doesn't search current line for the next occurrence of parenthesis

### ISSUE THREAD

**Issue by vasiakorobkin** [player-two/brackets-vim#10]
Suppose that I just moved to  the begining of this line in normal mode:

> background-color: rgba(0, 0, 0, 0.7);

And I want to edit rgba values given in parenthesis.
In vim I can just use `ci)`, there is no need to place cursor inside parenthesis, because vim will automatically search for the next occurrence of them.
When I'm trying to use brackets-vim v0.3.0 in Brackets v1.0 this feature doesn't work, so I have to use `f(` prior to using `ci)` to place my cursor inside parenthesis.
That's rather frustrating for me.
I haven't checked other text object motions and operators due to the lack of time, but it could be a common problem for all line-wise text object motions with any operator.

**Comment by player-two** [comment]
Hi @vasiakorobkin,
This extension is not intended to add vim keybindings to the Brackets editor. Brackets uses [CodeMirror](https://github.com/codemirror/CodeMirror) for the text editing, and brackets-vim provides access the the [vim keybindings that ship with CodeMirror](https://github.com/codemirror/CodeMirror/blob/master/keymap/vim.js) as well as adding some vim commands.  I'm going to close this and issue #11 for being out of scope, but feel free to create the issue in the CodeMirror repo.
