### ISSUE TITLE
The cursor is disapeared when I move into the HTML Tag

### ISSUE THREAD

**Issue by cmgddd** [player-two/brackets-vim#12]
![qq](https://cloud.githubusercontent.com/assets/2402885/5549433/82dfbe2a-8bc5-11e4-97a8-bd3de0fa6474.png)
perfer to 
![qq](https://cloud.githubusercontent.com/assets/2402885/5549452/0aa9d228-8bc6-11e4-8031-8f9b13cb581c.png)

**Comment by misaxi** [comment]
I can reproduce the bug with the parenthesis. This bug is really disturbing, not sure if this is fixable?

![image](https://cloud.githubusercontent.com/assets/767799/5697620/f8b04ad8-9a49-11e4-97c4-f9ed85318787.png)

**Comment by leedorian** [comment]
Same issue here, I think it's a critical issue.

**Comment by Siafu** [comment]
I have this issue as well. Like brackets but I love vim :(
