### ISSUE TITLE
Remove custom implementation of splitting editors

### ISSUE THREAD

**Issue by sbruchmann** [player-two/brackets-vim#4]
Hi @megalord,

the [Brackets](https://github.com/adobe/brackets) team is currently working on the official implementation of editor splitting, that will be available to extension authors, which will make your custom implementation obsolete.

You can see the current state of the feature at [Trello](https://trello.com/c/2DWV5tEX/1277-splitview-migrate-workingset-management-to-mainviewmanager) and [jeff/splitview-merge](https://github.com/adobe/brackets/tree/jeff/splitview-merge) respectively. There are also [architectural notes](https://github.com/adobe/brackets/wiki/SplitView-Architecture-Notes) available.

I’d be happy to send a pull request that removes your implementation and/or implements the official implementation as soon as it’s landed in master.

**Comment by player-two** [comment]
Hello @sbruchmann !

Thank you for all the details.  I had heard this would be coming, but I was not aware it was already under development.  I am going to leave my implementation as is for now, but I will refactor to use Brackets' own splitting feature once it is released.  I'll keep an eye on this.
