### ISSUE TITLE
RTE in extension

### ISSUE THREAD

**Issue by JeffryBooher** [player-two/brackets-vim#6]
Hey,
I tried this extension with the splitview branch and I get an RTE when trying to do `:vsp`.  You referenced the work in your notes but wanted to give you a heads up that it's just about ready to land in master if you're curious to see it in action.

Jeff/splitview-factory is the branch to work on.  The extension still works great just that one issue which throws and exception in both master and the splitview branches.

Thanks!

**Comment by player-two** [comment]
Ok, thanks for the notification!  I will start looking into the new API for view management and attempt to migrate my hackish splitting over to the Brackets feature.
