### ISSUE TITLE
Escape Key Doesn't Exit Insert Mode

### ISSUE THREAD

**Issue by roblevintennis** [player-two/brackets-vim#8]
I'm on 10.9.5 osx macbook pro, and I have the enable vim in file menu checked. I can't seem to reliably toggle between insert and command mode, and escape does nothing. I saw a shim in the code with a comment for handling escape. Is there another way I'm supposed to get in and out of insert/command mode? I'm used to escape/i per typical vim usage.

UPDATE: I noticed https://github.com/daveosborne/brackets-vimderbar which proclaims to support escape key. Is this meant to be used in tandem with that extension?

**Comment by player-two** [comment]
This plugin is an alternative to vimderbar, and I doubt they would play nice together.  I do most of my development in Ubuntu, but I'll see if I can duplicate the issue.  What version of Brackets are you using?

**Comment by roblevintennis** [comment]
@megalord thanks:
Release 1.0 build 1.0.0-15191 (release 3f2eb90a4) 
build timestamp: Fri Oct 31 2014 14:26:26 GMT-0700

**Comment by fluffywaffles** [comment]
Since Brackets' 1.0 release, I have also had trouble with escape key not exiting insert mode.
Same release, but on Ubuntu 14.04 LTS.

Release 1.0 experimental build 1.0.0-15191 (release 3f2eb90a4) 
build timestamp: Fri Oct 31 2014 14:19:23 GMT-0700

**Comment by roblevintennis** [comment]
@megalord working great > I updated via extension manager ... thanks!!!

**Comment by retsi101** [comment]
Anyone still having this issue? I'm running Brackets 1.8 here
